/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.96
 * Generated at: 2020-03-22 14:11:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

    String path = request.getContextPath();
    String basePath = request.getScheme() + "://"
            + request.getServerName() + ":" + request.getServerPort()
            + path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<link rel=\"shortcut icon\" href=\"static/images/huashao.png\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\r\n");
      out.write("<title>登录页面</title>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/js/jquery-2.1.0.min.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/js/easyform.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null, false));
      out.write("/static/css/style.css\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<br>\r\n");
      out.write("<div class=\"form-div\">\r\n");
      out.write("    <form id=\"reg-form\" method=\"post\">\r\n");
      out.write("        <table>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>用户号</td>\r\n");
      out.write("                <td><input type=\"text\" name=\"login_username\" id=\"uid\" message=\"请输入11位手机号\" maxlength=\"11\">\r\n");
      out.write("                </td>\r\n");
      out.write("            </tr>\r\n");
      out.write("            <tr>\r\n");
      out.write("                <td>密&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;码</td>\r\n");
      out.write("                <td><input type=\"password\" name=\"login_password\" id=\"psw1\" message=\"密码必须为6位\" maxlength=\"6\"></td>\r\n");
      out.write("            </tr>\r\n");
      out.write("        </table>\r\n");
      out.write("        <div class=\"input-group\">\r\n");
      out.write("\t        <input type=\"hidden\" id=\"login_status\">\r\n");
      out.write("\t    </div>\r\n");
      out.write("\t\t<div class=\"buttons\">\r\n");
      out.write("\t\t\t<input value=\"登录\" type=\"submit\" style=\"margin-right:20px; margin-top:20px;\" id=\"addUser\">\r\n");
      out.write("\t\t\t<input value=\"返回首页\" type=\"button\" style=\"margin-right:45px; margin-top:20px;\" onclick=\"fanhui()\">\r\n");
      out.write("        </div>\r\n");
      out.write("        <br class=\"clear\">\r\n");
      out.write("    </form>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function () {\r\n");
      out.write("    $('#addUser').click(function () {\r\n");
      out.write("        $.ajax({\r\n");
      out.write("            type: \"post\",\r\n");
      out.write("            url: \"login\",\r\n");
      out.write("            data: {\r\n");
      out.write("            \tlogin_username: $(\"#uid\").val(),\r\n");
      out.write("            \tlogin_password: $(\"#psw1\").val(),\r\n");
      out.write("            },\r\n");
      out.write("            dataType: \"JSON\",\r\n");
      out.write("            async: false,\r\n");
      out.write("            beforeSend: function () {\r\n");
      out.write("                alert(\"正在提交\");\r\n");
      out.write("            },\r\n");
      out.write("            success: function (data) {\r\n");
      out.write("            \tif(data == 1){\r\n");
      out.write("            \t\talert(\"用户号或密码不能为空\");\r\n");
      out.write("            \t}else if (data == 2) {\r\n");
      out.write("                    alert(\"用户号必须是11位\");\r\n");
      out.write("                }else if (data == 3) {\r\n");
      out.write("                    alert(\"密码必须是6位\");\r\n");
      out.write("                }else if (data == 4) {\r\n");
      out.write("                    alert(\"用户不存在\");\r\n");
      out.write("                }else if (data == 5) {\r\n");
      out.write("                    alert(\"您的账号已冻结，请联系管理员\");\r\n");
      out.write("                }else if (data == 6) {\r\n");
      out.write("                    alert(\"密码不正确\");\r\n");
      out.write("                }else{\r\n");
      out.write("                    alert(\"登录成功\")\r\n");
      out.write("                    window.location.href=\"toFindFewFlowers\";\r\n");
      out.write("                }\r\n");
      out.write("            },\r\n");
      out.write("            error: function () {\r\n");
      out.write("                alert(\"提交失败\");\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("    })\r\n");
      out.write("})\r\n");
      out.write("$(document).ready(function(){\r\n");
      out.write("\t$('#reg-form').easyform();\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function fanhui(){\r\n");
      out.write("\twindow.location.href=\"tohomepage\";\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
